package Thread;

class ThreadPriority extends Thread
{
    public void run()
    {
        for(int i=1;i<=5;i++) {
            System.out.println(Thread.currentThread().getPriority());
        }
    }
}

public class ThreadPrioritiess {
    public static void main(String[] args) {

        //Thread.currentThread().setPriority(8);//if we give >10, then illegalArumentException will come

        ThreadPriority tp = new ThreadPriority();
        tp.setPriority(10);

        tp.start();

        for(int i=1;i<=5;i++) {
            System.out.println(Thread.currentThread().getPriority());
        }




    }
}

/*
===>Thread Priorities: Every Thread has some priority, it may defualt priority generated by JVM or customized priority
                       provided by programmer.

===> Range: 1-10

===> We have 3 types of priority
     1. Thread.MIN_PRIORITY(1)
     2. Thread.NORM_PRIORITY(5)
     3. Thread.MAX_PRIORITY(10)


===>Purpose: Thread Schedular use Thread Priority to provide processor to thread.
             Thread Schedular gives chance to Highest priority thread to excecute fisrt.

===>Note: If 2 threads having same priority, then we can not excpect which thread will execute first.
          It will decide by T.S and T.S can give chance to anyone.


===>Default Priority of main thread is 5.

===>Default Priority of child thread depends on its Parent thread Priority, whatever Priority have parents same Priority
    will be for child thread.

===> Some Operating System can not provide support for Thread priority.
 */